# Category REST API
@baseUrl=http://localhost:1337
@id=w1ronmdbir6kz368vp3g93rv

### List all categories
GET {{baseUrl}}/api/categories

### List all categories with populated relations
GET {{baseUrl}}/api/categories?populate=*&locale=en

### Get category by ID
GET {{baseUrl}}/api/categories/{{id}}

### Get category by ID with populated relations
GET {{baseUrl}}/api/categories?populate[localizations][populate]