@baseUrl=http://localhost:1337
@id=lihec8py7e9qtqppcsw1xz23

### List all products
GET {{baseUrl}}/api/productos

### List all products
GET {{baseUrl}}/api/productos

### Get product by ID with populated relations
GET {{baseUrl}}/api/productos/{{id}}?populate=*

### Get product by ID
GET {{baseUrl}}/api/productos/{{id}}


### Obtener producto por ID
GET {{baseUrl}}/api/productos/{{id}}


