# Subcategoria REST API
@baseUrl=http://localhost:1337
@id=gf6t1uhyeavusac8eyqo0b0s
@categoriaId=viv04z4bste7wdz9ibkcgy61

### List all subcategories
GET {{baseUrl}}/api/subcategorias

### List subcategories with populated category
GET {{baseUrl}}/api/subcategorias?populate=categoria

### Get subcategory by ID
GET {{baseUrl}}/api/subcategorias/{{id}}

### Get subcategory with populated category
GET {{baseUrl}}/api/subcategorias/{{id}}?populate=categoria

